### ISSUE TITLE
Support for kernel 6.13

### ISSUE THREAD

**Issue by mateusz-pietras** [DIGImend/digimend-kernel-drivers#713]
Hello, I am having trouble installing the drivers using dkms method on Fedora 41 with kernel: Linux 6.13.6-200.fc41.x86_64

The installation fails with:
```
Error! Bad return status for module build on kernel: 6.13.6-200.fc41.x86_64 (x86_64)
Consult /var/lib/dkms/digimend/13/build/make.log for more information.
make: *** [Makefile:101: dkms_modules_install] Error 10
```

Contents of make.log
```
DKMS (dkms-3.1.5) make.log for digimend/13 for kernel 6.13.6-200.fc41.x86_64 (x86_64)
Mon Mar 24 10:36:22 PM CET 2025
Cleaning build area
# command: make -C /lib/modules/6.13.6-200.fc41.x86_64/build M=/var/lib/dkms/digimend/13/build clean
make[1]: Entering directory '/usr/src/kernels/6.13.6-200.fc41.x86_64'
make[2]: Entering directory '/var/lib/dkms/digimend/13/build'
make[2]: Leaving directory '/var/lib/dkms/digimend/13/build'
make[1]: Leaving directory '/usr/src/kernels/6.13.6-200.fc41.x86_64'

# exit code: 0
# elapsed time: 00:00:00
Building module(s)
# command: make -j20 KERNELRELEASE=6.13.6-200.fc41.x86_64 KVERSION=6.13.6-200.fc41.x86_64
make[1]: Entering directory '/var/lib/dkms/digimend/13/build'
make -C /lib/modules/6.13.6-200.fc41.x86_64/build M=/var/lib/dkms/digimend/13/build modules
make[2]: Entering directory '/usr/src/kernels/6.13.6-200.fc41.x86_64'
make[3]: Entering directory '/var/lib/dkms/digimend/13/build'
  CC [M]  hid-kye.o
  CC [M]  hid-uclogic-core.o
  CC [M]  hid-uclogic-rdesc.o
  CC [M]  hid-uclogic-params.o
  CC [M]  hid-polostar.o
  CC [M]  hid-viewsonic.o
hid-uclogic-rdesc.c:19:10: fatal error: asm/unaligned.h: No such file or directory
   19 | #include <asm/unaligned.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[5]: *** [/usr/src/kernels/6.13.6-200.fc41.x86_64/scripts/Makefile.build:196: hid-uclogic-rdesc.o] Error 1
make[5]: *** Waiting for unfinished jobs....
hid-kye.c:790:25: error: initialization of ‘const __u8 * (*)(struct hid_device *, __u8 *, unsigned int *)’ {aka ‘const unsigned char * (*)(struct hid_device *, unsigned char *, unsigned int *)’} from incompatible pointer type ‘__u8 * (*)(struct hid_device *, __u8 *, unsigned int *)’ {aka ‘unsigned char * (*)(struct hid_device *, unsigned char *, unsigned int *)’} [-Wincompatible-pointer-types]
  790 |         .report_fixup = kye_report_fixup,
      |                         ^~~~~~~~~~~~~~~~
hid-kye.c:790:25: note: (near initialization for ‘kye_driver.report_fixup’)
hid-uclogic-params.c:22:10: fatal error: asm/unaligned.h: No such file or directory
   22 | #include <asm/unaligned.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[5]: *** [/usr/src/kernels/6.13.6-200.fc41.x86_64/scripts/Makefile.build:196: hid-kye.o] Error 1
make[5]: *** [/usr/src/kernels/6.13.6-200.fc41.x86_64/scripts/Makefile.build:196: hid-uclogic-params.o] Error 1
hid-polostar.c:210:25: error: initialization of ‘const __u8 * (*)(struct hid_device *, __u8 *, unsigned int *)’ {aka ‘const unsigned char * (*)(struct hid_device *, unsigned char *, unsigned int *)’} from incompatible pointer type ‘__u8 * (*)(struct hid_device *, __u8 *, unsigned int *)’ {aka ‘unsigned char * (*)(struct hid_device *, unsigned char *, unsigned int *)’} [-Wincompatible-pointer-types]
  210 |         .report_fixup = polostar_report_fixup,
      |                         ^~~~~~~~~~~~~~~~~~~~~
hid-polostar.c:210:25: note: (near initialization for ‘polostar_driver.report_fixup’)
hid-viewsonic.c:123:25: error: initialization of ‘const __u8 * (*)(struct hid_device *, __u8 *, unsigned int *)’ {aka ‘const unsigned char * (*)(struct hid_device *, unsigned char *, unsigned int *)’} from incompatible pointer type ‘__u8 * (*)(struct hid_device *, __u8 *, unsigned int *)’ {aka ‘unsigned char * (*)(struct hid_device *, unsigned char *, unsigned int *)’} [-Wincompatible-pointer-types]
  123 |         .report_fixup = viewsonic_report_fixup,
      |                         ^~~~~~~~~~~~~~~~~~~~~~
hid-viewsonic.c:123:25: note: (near initialization for ‘viewsonic_driver.report_fixup’)
make[5]: *** [/usr/src/kernels/6.13.6-200.fc41.x86_64/scripts/Makefile.build:196: hid-polostar.o] Error 1
make[5]: *** [/usr/src/kernels/6.13.6-200.fc41.x86_64/scripts/Makefile.build:196: hid-viewsonic.o] Error 1
hid-uclogic-core.c:577:25: error: initialization of ‘const __u8 * (*)(struct hid_device *, __u8 *, unsigned int *)’ {aka ‘const unsigned char * (*)(struct hid_device *, unsigned char *, unsigned int *)’} from incompatible pointer type ‘__u8 * (*)(struct hid_device *, __u8 *, unsigned int *)’ {aka ‘unsigned char * (*)(struct hid_device *, unsigned char *, unsigned int *)’} [-Wincompatible-pointer-types]
  577 |         .report_fixup = uclogic_report_fixup,
      |                         ^~~~~~~~~~~~~~~~~~~~
hid-uclogic-core.c:577:25: note: (near initialization for ‘uclogic_driver.report_fixup’)
make[5]: *** [/usr/src/kernels/6.13.6-200.fc41.x86_64/scripts/Makefile.build:196: hid-uclogic-core.o] Error 1
make[4]: *** [/usr/src/kernels/6.13.6-200.fc41.x86_64/Makefile:2024: .] Error 2
make[3]: *** [/usr/src/kernels/6.13.6-200.fc41.x86_64/Makefile:263: __sub-make] Error 2
make[3]: Leaving directory '/var/lib/dkms/digimend/13/build'
make[2]: *** [Makefile:263: __sub-make] Error 2
make[2]: Leaving directory '/usr/src/kernels/6.13.6-200.fc41.x86_64'
make[1]: *** [Makefile:25: modules] Error 2
make[1]: Leaving directory '/var/lib/dkms/digimend/13/build'

# exit code: 2
# elapsed time: 00:00:01
```

Thank you in advance.

**Comment by gleb0g** [comment]
Hello, @mateusz-pietras !
It looks like a very similar issue was mentioned here in [#706](https://github.com/DIGImend/digimend-kernel-drivers/issues/706).To make a long story short - the fix for that header file `unaligned.h` was merged with PR [707](https://github.com/DIGImend/digimend-kernel-drivers/pull/707), but it's not yet included in a release, which is likely where you attempted to install from. So just try to build from the master branch instead.
